### ISSUE TITLE
init error

### ISSUE THREAD

**Issue by loganbest** [MJL85/mnet#1]
I'm running Python 2.7.10.

```
 $ ./mnet-graph.py -r x.x.x.x -f gscnetwork.svg -d 10 -c ./mnet.conf
MNet-Graph v0.1
Written by Michael Laforest <mjlaforest@gmail.com>

Config file: ./mnet.conf
  Root node: x.x.x.x
Output file: gscnetwork.svg
Crawl depth: 10
Diagram title: MNet Network Diagram

Traceback (most recent call last):
  File "./mnet-graph.py", line 666, in <module>
    main(sys.argv[1:])
  File "./mnet-graph.py", line 487, in main
    crawl_node(opt_root_ip, opt_depth)
  File "./mnet-graph.py", line 256, in crawl_node
    system_name = shorten_host_name(get_snmp_val(ip, OID_SYSNAME) or 'UNKNOWN')
  File "./mnet-graph.py", line 109, in get_snmp_val
    cmdgen.CommunityData(community),
TypeError: __init__() takes at least 3 arguments (2 given)
```

**Comment by MJL85** [comment]
What version of PySNMP are you using?  I believe you can check it with the below.  I've tested it with 4.2.5.

```
michael# python2
Python 2.7.8 (default, Dec  4 2014, 15:36:21)
[GCC 4.2.1 Compatible FreeBSD Clang 3.4.1 (tags/RELEASE_34/dot1-final 208032)] on freebsd10
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysnmp
>>> print pysnmp.__version__
4.2.5
>>> quit()
```

**Comment by loganbest** [comment]
4.2.1

**Comment by loganbest** [comment]
Any luck with this?

NINJA EDIT: This is particularly erroring on OSX 10.7.5, but I get the same on 10.10 as well

**Comment by liftedkilt** [comment]
Just for kicks - did you update to the new version of the script? You'll
need to install netaddr for python as well (easy_install netaddr)

**Comment by MJL85** [comment]
Added package to pip which should hopefully fix this issue.  If it doesn't please open a new ticket.  Closing because there have been so many revisions in the past week I doubt this is still relevant.
