### ISSUE TITLE
Couldn't import dot_parser, loading of dot files will not be possible.

### ISSUE THREAD

**Issue by waukeerules** [MJL85/mnet#20]
I'm getting the following error when I run mnet.py. What am I missing? I am using Python version 3.6.1. 

Traceback (most recent call last):
  File "C:\Program Files\Python36\Scripts\mnet.py", line 32, in <module>
    import mnetsuite
  File "C:\Program Files\Python36\lib\site-packages\mnetsuite\__init__.py", line 1, in <module>
    from .graph		import mnet_graph
  File "C:\Program Files\Python36\lib\site-packages\mnetsuite\graph.py", line 34, in <module>
    from snmp import *
ModuleNotFoundError: No module named 'snmp'

**Comment by waukeerules** [comment]
I see now mnet is not supported in 3.6. Any plans to change that?
