### ISSUE TITLE
Errors on all platforms, all seed devices

### ISSUE THREAD

**Issue by heymex** [MJL85/mnet#22]
I am having a heck of a time getting this up and going.  After sorting through some pydot/pydot2 issues, I was able to get the script to at least execute.  However, every time I try to run it, I get the following errors:

```
Traceback (most recent call last):
  File "/usr/local/bin/mnet.py", line 198, in <module>
    main(sys.argv[1:])
  File "/usr/local/bin/mnet.py", line 67, in main
    graph(argv[1:])
  File "/usr/local/bin/mnet.py", line 129, in graph
    graph.crawl(opt_root_ip)
  File "/usr/local/lib/python2.7/dist-packages/mnetsuite/graph.py", line 92, in crawl
    n.query_node()
  File "/usr/local/lib/python2.7/dist-packages/mnetsuite/node.py", line 485, in query_node
    self._get_chassis_info()
  File "/usr/local/lib/python2.7/dist-packages/mnetsuite/node.py", line 809, in _get_chassis_info
    self.ios = self._format_ios_ver(self.ios)
  File "/usr/local/lib/python2.7/dist-packages/mnetsuite/node.py", line 831, in _format_ios_ver
    img_s = re.search('(Version:? |CCM:)([^ ,$]*)', img)
  File "/usr/lib/python2.7/re.py", line 142, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or buffer
```
Any idea what I am doing wrong here?

**Comment by slashrjl** [comment]
looks to be the same issue as https://github.com/MJL85/mnet/issues/11

**Comment by LaurentDumont** [comment]
Looks like I'm hitting the same  issue.

**Comment by LaurentDumont** [comment]
Just tried the latest master directly from Github and everything seems to be working. I'll dig into this a bit more to see if all the features are there!
