### ISSUE TITLE
Script launching issue - Windows

### ISSUE THREAD

**Issue by AxiansMRS** [MJL85/mnet#37]
Hello guys,

After Python 3.7 installation on Windows 10 Enterprise, I'm trying to test this script on powershell.

I've specified the snmp v2 community on natlas.conf & also a permit ip xx.xx.xx.xx/24 in the discover part.

PS C:\Users\Thierry.ROUX\Desktop\Network Atlas> .\natlas-cli.py tracemac -n xx.xx.xx.xx -m xxxx.xxxx.xxxx

No result, I can see a black cmd windows which is here for 2 seconds and then nothing.

Same issue with diagram module with an expected output file.

Could you please assist me ?

Thanks in advance for your actions.

Best regards,

Thierry

**Comment by AxiansMRS** [comment]
By the way, when I use Windows CMD instead of Powershell, I got these logs : 

Traceback (most recent call last):
  File "C:\Users\Thierry.ROUX\Desktop\Network Atlas\natlas-cli.py", line 35, in <module>
    import natlas
  File "C:\Users\Thierry.ROUX\Desktop\Network Atlas\natlas\__init__.py", line 2, in <module>
    from .natlas import natlas
  File "C:\Users\Thierry.ROUX\Desktop\Network Atlas\natlas\natlas.py", line 35, in <module>
    from .network import natlas_network
  File "C:\Users\Thierry.ROUX\Desktop\Network Atlas\natlas\network.py", line 29, in <module>
    from .util import *
  File "C:\Users\Thierry.ROUX\Desktop\Network Atlas\natlas\util.py", line 34, in <module>
    from .snmp import *
  File "C:\Users\Thierry.ROUX\Desktop\Network Atlas\natlas\snmp.py", line 27, in <module>
    from pysnmp.entity.rfc3413.oneliner import cmdgen
ModuleNotFoundError: No module named 'pysnmp'

**Comment by AxiansMRS** [comment]
I've noticed that I've missed some libraries, now it's ok for this, but I've got another issue : 

natlas v0.12.1
Michael Laforest <mjlaforest@gmail.com>
Python 3.7.0

Expecting value: line 11 column 2 (char 160)
