### ISSUE TITLE
Error when trying to run diagram module

### ISSUE THREAD

**Issue by ntwrkguy** [MJL85/mnet#65]
python3 natlas-cli.py diagram -r 10.0.0.1 -o diagram.svg
natlas v0.12.1
Michael Laforest <mjlaforest@gmail.com>
Python 3.6.8

Expecting value: line 8 column 2 (char 127)

No other information is provided for the error

**Comment by sjbeskur** [comment]
I too had this same issue and after stepping through the code It turned out that my natlas.conf file had an error (trailing common in one of the arrays).    Here is a copy of my natlas config for your referrence:

`{
	"snmp" : [
		{ "community":"public_ro",		"ver":2 }
	],
	"domains" : [
	],
	"discover" : [
		"permit ip 192.168.88.0/24"
	],
	"diagram" : {
		"node_text_size" : 10,
		"link_text_size" : 9,
		"title_text_size" : 15,
		"get_stack_members" : 0,
		"get_vss_members" : 0,
		"expand_stackwise" : 0,
		"expand_vss" : 1,
		"expand_lag" : 1,
		"group_vpc" : 0
	}
}`

**Comment by mav51** [comment]
Thanks for the wonderful job, I have a problem with diagram module.
I get this error on every single IP address 

Back filling node details...
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
"dot" with args ['-Tsvg', '/tmp/tmpeyo79kwj'] returned code: 1

stdout, stderr:
 b''
b"Error: /tmp/tmpeyo79kwj: syntax error in line 24 near '>'\n"

Traceback (most recent call last):
  File "natlas-cli.py", line 305, in <module>
    main(sys.argv[1:])
  File "natlas-cli.py", line 96, in main
    exec_mod(mod, argv[1:])
  File "natlas-cli.py", line 167, in exec_mod
    modret = module.entryfunc(natlas_obj, argv)
  File "./modules/diagram.py", line 88, in mod_entry
    if (opt_output != None):    natlas_obj.write_diagram(opt_output, opt_title)
  File "/home/kali/skyforce/pentest/scripts/cisco/natlas/natlas/natlas.py", line 125, in write_diagram
    self.diagram.generate(output_file, diagram_title)
  File "/home/kali/skyforce/pentest/scripts/cisco/natlas/natlas/output_diagram.py", line 108, in generate
    output_func(f)
  File "/usr/lib/python3/dist-packages/pydot.py", line 1736, in new_method
    self.write(
  File "/usr/lib/python3/dist-packages/pydot.py", line 1825, in write
    s = self.create(prog, format, encoding=encoding)
  File "/usr/lib/python3/dist-packages/pydot.py", line 1953, in create
    assert process.returncode == 0, process.returncode
AssertionError: 1
